from __future__ import annotations


VERIFIED_ON = "2026-04-14"

HEADER_FIELDS = [
    ("source_name", "Source Name"),
    ("lifecycle", "Lifecycle"),
    ("business_area", "Business Area"),
    ("target_capability", "Target Capability / Planned Feature"),
    ("domain", "Domain"),
    ("repo_status", "Repo Status"),
    ("runtime_surface", "Runtime Surface"),
    ("mgmt_priority", "Mgmt Priority"),
    ("mgmt_recommendation", "Mgmt Recommendation"),
    ("provided_data_types", "Provided Data Types"),
    ("description", "Description"),
    ("repo_ids_or_code_paths", "Repo IDs / Code Paths"),
    ("homepage_url", "Homepage URL"),
    ("registration_url", "Registration URL"),
    ("api_or_docs_endpoint", "API / Docs / Data Endpoint"),
    ("subscription_fees_or_access_model", "Subscription Fees / Access Model"),
    ("auth_model", "Auth Model"),
    ("commercial_or_license_notes", "Commercial / License Notes"),
    ("integration_effort", "Integration Effort"),
    ("legal_or_procurement_risk", "Legal / Procurement Risk"),
    ("current_repo_caveats_or_rationale", "Current Repo Caveats / Rationale"),
    ("last_verified", "Last Verified"),
    ("mgmt_approval_status", "Mgmt Approval Status"),
    ("mgmt_approval_notes", "Mgmt Approval Notes"),
]

HEADERS = [label for _, label in HEADER_FIELDS]
FIELD_KEYS = {key for key, _ in HEADER_FIELDS}

CURRENT_IMPLEMENTED = "Current - Implemented"
CURRENT_OPTIONAL = "Current - Optional / Commercial"
CURRENT_FALLBACK = "Current - Marketplace Fallback"
FUTURE_CANDIDATE = "Future Candidate"

HIGH = "High"
MEDIUM = "Medium"
LOW = "Low"

QUOTE_BASED = "Quote-based / contact sales"
MARKETPLACE = "Marketplace pricing / listing-dependent"
PLANNED_IMAGERY = "No code yet; planned for imagery connectors, change analytics, and evidence packs"
PLANNED_CONSTRUCTION = "No code yet; planned for AOI enrichment, construction analytics, and evidence packs"
PLANNED_MARITIME = "No code yet; planned for dark ships, chokepoints, vessel intelligence, and investigations"
PLANNED_AIR = "No code yet; planned for src/connectors/airspace_connector.py replacement and aviation workflows"
PLANNED_ORBIT = "No code yet; planned replacement for src/connectors/orbit_connector.py"
PLANNED_CAMERA = "No code yet; planned for src/api/cameras.py, src/api/detections.py, and absence analytics"
PLANNED_INVEST = "No code yet; planned for investigations, entity resolution, sanctions screening, and evidence packs"
PLANNED_STRIKE = "No code yet; planned replacement for src/connectors/strike_connector.py and conflict workflows"
PLANNED_JAMMING = "No code yet; planned replacement for src/connectors/jamming_connector.py and signal-risk workflows"
PLANNED_ENV = "No code yet; planned for resilience, weather, hazard, terrain, and operational context layers"
PLANNED_SUPPLY = "No code yet; planned for chokepoints, maritime logistics, and supply-chain intelligence"


def source_row(**kwargs: str) -> list[str]:
    unexpected = set(kwargs) - FIELD_KEYS
    if unexpected:
        raise KeyError(f"Unexpected fields: {sorted(unexpected)}")
    values = {
        "last_verified": VERIFIED_ON,
        "mgmt_approval_status": "",
        "mgmt_approval_notes": "",
    }
    values.update(kwargs)
    return [str(values.get(key, "")) for key, _ in HEADER_FIELDS]


def current_row(**kwargs: str) -> list[str]:
    return source_row(**kwargs)


def future_row(**kwargs: str) -> list[str]:
    defaults = {
        "lifecycle": FUTURE_CANDIDATE,
        "repo_status": "Not implemented in repo; candidate source",
        "runtime_surface": "Planned connector / workflow integration",
        "mgmt_recommendation": "Research and shortlist",
    }
    defaults.update(kwargs)
    return source_row(**defaults)


ROWS = [
    current_row(
        source_name="Copernicus Data Space Ecosystem (CDSE)",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Construction Monitoring / Imagery",
        target_capability="Baseline optical imagery and change detection",
        domain="Imagery",
        repo_status="Live when SENTINEL2_CLIENT_ID and SENTINEL2_CLIENT_SECRET are configured",
        runtime_surface="App startup imagery provider + V2 connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Sentinel-2 L2A optical multispectral imagery, STAC search, COG assets",
        description="Official Copernicus Sentinel-2 path for live optical imagery search and streaming.",
        repo_ids_or_code_paths="app/providers/sentinel2.py | src/connectors/sentinel2.py",
        homepage_url="https://dataspace.copernicus.eu/",
        registration_url="https://dataspace.copernicus.eu/",
        api_or_docs_endpoint="https://stac.dataspace.copernicus.eu/v1",
        subscription_fees_or_access_model="Free/open access; account registration required for OAuth client creation",
        auth_model="OAuth2 client credentials",
        commercial_or_license_notes="Official first-party source; favorable for production approval",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Keep as primary open optical source; requires credential hygiene and uptime monitoring",
    ),
    current_row(
        source_name="Earth Search (Element 84)",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Construction Monitoring / Imagery",
        target_capability="Open cloud imagery catalog fallback",
        domain="Imagery",
        repo_status="Always registered at app startup",
        runtime_surface="App startup V2 connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Public STAC for Sentinel-2, Landsat Collection 2, and open cloud-hosted data",
        description="Open cloud-native imagery catalog that removes the need for first-party auth for many public assets.",
        repo_ids_or_code_paths="src/connectors/earth_search.py",
        homepage_url="https://element84.com/earth-search",
        registration_url="Not required for public access",
        api_or_docs_endpoint="https://earth-search.aws.element84.com/v1",
        subscription_fees_or_access_model="Free public STAC endpoint",
        auth_model="None",
        commercial_or_license_notes="Public endpoint; no guaranteed service level on the shared service",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Good low-friction fallback, but not contracted infrastructure",
    ),
    current_row(
        source_name="Microsoft Planetary Computer",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Construction Monitoring / Imagery",
        target_capability="Open imagery catalog redundancy",
        domain="Imagery",
        repo_status="Always registered at app startup",
        runtime_surface="App startup V2 connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Public STAC metadata catalog for Earth science datasets",
        description="Second open imagery/catalog path alongside Earth Search and CDSE.",
        repo_ids_or_code_paths="src/connectors/planetary_computer.py",
        homepage_url="https://planetarycomputer.microsoft.com/",
        registration_url="Not required for public catalog access",
        api_or_docs_endpoint="https://planetarycomputer.microsoft.com/api/stac/v1",
        subscription_fees_or_access_model="Public catalog without auth; higher-limit/commercial arrangements are separate",
        auth_model="None by default; optional subscription key",
        commercial_or_license_notes="Strong public utility; dedicated support model should be confirmed if promoted to primary dependency",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Operationally valuable as a second open catalog, but not a contracted service today",
    ),
    current_row(
        source_name="USGS LandsatLook / Landsat Collection 2",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Construction Monitoring / Imagery",
        target_capability="Large-area optical imagery fallback",
        domain="Imagery",
        repo_status="Always available in repo for search; optional account for ERS workflows",
        runtime_surface="App startup imagery provider + V2 connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Landsat Collection 2 Level-2 optical multispectral imagery via STAC",
        description="Public large-area optical imagery source and fallback when Sentinel is unavailable.",
        repo_ids_or_code_paths="app/providers/landsat.py | src/connectors/landsat.py",
        homepage_url="https://www.usgs.gov/landsat-missions/landsat-data-access",
        registration_url="https://ers.cr.usgs.gov/",
        api_or_docs_endpoint="https://landsatlook.usgs.gov/stac-server",
        subscription_fees_or_access_model="No-charge public search/download; optional USGS account for archive tools",
        auth_model="None for STAC search; optional USGS account for ERS/M2M",
        commercial_or_license_notes="US government/public-domain style access is favorable",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Lower spatial resolution than Sentinel-2; best for large sites",
    ),
    current_row(
        source_name="Vantor / former Maxar SecureWatch / MGP Pro",
        lifecycle=CURRENT_OPTIONAL,
        business_area="Construction Monitoring / Premium Imagery",
        target_capability="Very-high-resolution optical imagery",
        domain="Imagery",
        repo_status="Optional commercial provider when MAXAR_API_KEY is set",
        runtime_surface="Optional imagery provider",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial quote required",
        provided_data_types="Commercial high-resolution optical imagery",
        description="Premium small-area imagery option for urban parcels and sensitive targets.",
        repo_ids_or_code_paths="app/providers/maxar.py",
        homepage_url="https://vantor.com/",
        registration_url="https://vantor.com/contact-us",
        api_or_docs_endpoint="Repo default endpoint: https://api.maxar.com/discovery/v1",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="API key",
        commercial_or_license_notes="Contractual licensing and redistribution controls apply",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Repo naming is stale versus current branding; procurement should revalidate product and endpoint assumptions",
    ),
    current_row(
        source_name="Planet Insights Platform / PlanetScope / SkySat",
        lifecycle=CURRENT_OPTIONAL,
        business_area="Construction Monitoring / Premium Imagery",
        target_capability="Near-daily commercial optical imagery and tasking",
        domain="Imagery",
        repo_status="Optional commercial provider when PLANET_API_KEY is set",
        runtime_surface="Optional imagery provider",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial quote required",
        provided_data_types="PlanetScope imagery, SkySat archive/tasking, subscriptions, platform processing",
        description="Premium imagery and tasking path with enterprise and self-serve motions.",
        repo_ids_or_code_paths="app/providers/planet.py",
        homepage_url="https://www.planet.com/",
        registration_url="https://insights.planet.com/sign-up/",
        api_or_docs_endpoint="https://api.planet.com/data/v1",
        subscription_fees_or_access_model="Free trial exists; ongoing spend mixes AUM, tasking, and processing-unit pricing",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial licensing varies by product family and purchase route",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Budgeting is more complex than a single flat subscription line item",
    ),
    current_row(
        source_name="AISStream.io",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Maritime Intelligence",
        target_capability="Live AIS vessel tracking",
        domain="Telemetry",
        repo_status="Live when AISSTREAM_API_KEY is set",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="AIS vessel positions, vessel metadata, maritime incidents, SAR aircraft positions",
        description="Primary maritime live-track source in the repo.",
        repo_ids_or_code_paths="src/connectors/ais_stream.py | app/workers/tasks.py",
        homepage_url="https://aisstream.io/",
        registration_url="https://aisstream.io/authenticate",
        api_or_docs_endpoint="wss://stream.aisstream.io/v0/stream",
        subscription_fees_or_access_model="Official site markets access as free; no public paid tier confirmed",
        auth_model="API key over WebSocket",
        commercial_or_license_notes="Backend-only consumption is recommended and matches repo design",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Needs API key lifecycle management and websocket resiliency monitoring",
    ),
    current_row(
        source_name="OpenSky Network",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Aviation / Airspace",
        target_capability="Live aircraft telemetry",
        domain="Telemetry",
        repo_status="Always registered in app startup; credentials optional in repo",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=HIGH,
        mgmt_recommendation="Legal review required",
        provided_data_types="Aircraft state vectors from ADS-B, Mode-S, ADS-C, FLARM, and VHF sources",
        description="Primary aviation live-track source in the repo.",
        repo_ids_or_code_paths="src/connectors/opensky.py | app/workers/tasks.py",
        homepage_url="https://opensky-network.org/",
        registration_url="https://opensky-network.org/",
        api_or_docs_endpoint="https://opensky-network.org/api",
        subscription_fees_or_access_model="Public API exists, but commercial entities must license separately",
        auth_model="Optional username/password; some public access without auth",
        commercial_or_license_notes="Research/non-commercial-first terms unless separately licensed",
        integration_effort=LOW,
        legal_or_procurement_risk=HIGH,
        current_repo_caveats_or_rationale="Do not approve for commercial productization without terms and licensing review",
    ),
    current_row(
        source_name="GDELT 2.0",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Context / Investigations",
        target_capability="News-derived event and context enrichment",
        domain="Context / News",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Global news-derived events, themes, tone, entities, images, and quotes",
        description="Contextual signal layer for correlating reporting around AOIs.",
        repo_ids_or_code_paths="src/connectors/gdelt.py | app/workers/tasks.py",
        homepage_url="https://www.gdeltproject.org/",
        registration_url="Not required",
        api_or_docs_endpoint="https://api.gdeltproject.org/api/v2",
        subscription_fees_or_access_model="Free and open",
        auth_model="None",
        commercial_or_license_notes="Broad access model and strong contextual coverage",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Signal quality varies with news coverage and extraction accuracy",
    ),
    current_row(
        source_name="ACLED",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Conflict / Crisis Intelligence",
        target_capability="Conflict and instability event layer",
        domain="Public Record / Conflict",
        repo_status="Live only when ACLED credentials are configured",
        runtime_surface="Optional app startup connector + worker poller",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Approve conditionally",
        provided_data_types="Conflict, protest, political violence, and crisis event records",
        description="High-value conflict layer if access terms align with commercial use.",
        repo_ids_or_code_paths="src/connectors/acled.py | app/workers/tasks.py",
        homepage_url="https://acleddata.com/",
        registration_url="https://acleddata.com/user/register",
        api_or_docs_endpoint="https://acleddata.com/api/acled/read",
        subscription_fees_or_access_model="Free public access exists with limits; corporate/commercial use requires licensing",
        auth_model="Repo expects account credentials; current access model should be revalidated",
        commercial_or_license_notes="Usage rights vary by user class; commercial usage is not automatically covered",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=HIGH,
        current_repo_caveats_or_rationale="Repo comments likely reflect an older auth flow; confirm current terms before production use",
    ),
    current_row(
        source_name="USGS Earthquake Catalog / FDSN Event API",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Environment / Hazard",
        target_capability="Hazard context and event correlation",
        domain="Public Record / Hazard",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Earthquake event records with magnitude, depth, location, and update metadata",
        description="Straightforward public hazard feed with low approval risk.",
        repo_ids_or_code_paths="src/connectors/usgs_earthquake.py | app/workers/tasks.py",
        homepage_url="https://www.usgs.gov/programs/earthquake-hazards",
        registration_url="Not required",
        api_or_docs_endpoint="https://earthquake.usgs.gov/fdsnws/event/1",
        subscription_fees_or_access_model="Free public access",
        auth_model="None",
        commercial_or_license_notes="US government/public feed with favorable terms",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Useful mostly when environmental disruption matters to the workflow",
    ),
    current_row(
        source_name="NASA EONET",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Environment / Hazard",
        target_capability="Curated natural-event context",
        domain="Context / Hazard",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Natural-event metadata linked to related imagery sources",
        description="Context layer for storms, fires, volcanoes, dust, and related hazards.",
        repo_ids_or_code_paths="src/connectors/nasa_eonet.py | app/workers/tasks.py",
        homepage_url="https://eonet.gsfc.nasa.gov/",
        registration_url="Not required",
        api_or_docs_endpoint="https://eonet.gsfc.nasa.gov/api/v3",
        subscription_fees_or_access_model="Free/open NASA API",
        auth_model="None",
        commercial_or_license_notes="Low approval risk and easy onboarding",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Curated context rather than raw sensor telemetry",
    ),
    current_row(
        source_name="Open-Meteo",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Environment / Operations",
        target_capability="Weather forecast context",
        domain="Context / Weather",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Approve conditionally",
        provided_data_types="Weather forecast context; adjacent marine, air-quality, flood, and climate APIs",
        description="Useful weather layer for operational interpretation around sites and routes.",
        repo_ids_or_code_paths="src/connectors/open_meteo.py | app/workers/tasks.py",
        homepage_url="https://open-meteo.com/",
        registration_url="Not required for free tier",
        api_or_docs_endpoint="https://api.open-meteo.com/v1",
        subscription_fees_or_access_model="Free non-commercial tier plus paid customer/commercial API plans",
        auth_model="None for free tier; API key for commercial customer API",
        commercial_or_license_notes="Good functional fit; move off the free shared tier when usage becomes commercial/high-volume",
        integration_effort=LOW,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Commercial usage model depends on selected plan and traffic level",
    ),
    current_row(
        source_name="NGA Maritime Safety Information",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Maritime Intelligence",
        target_capability="Maritime safety warnings and NAVAREA notices",
        domain="Public Record / Maritime",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=HIGH,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Maritime safety and broadcast warning records",
        description="Public maritime warning layer already tuned for Gulf and nearby waters.",
        repo_ids_or_code_paths="src/connectors/nga_msi.py | app/workers/tasks.py",
        homepage_url="https://msi.nga.mil/",
        registration_url="Not required",
        api_or_docs_endpoint="https://msi.nga.mil/api/publications/broadcast-warn",
        subscription_fees_or_access_model="Free public access",
        auth_model="None",
        commercial_or_license_notes="Favorable government/public access model",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Structured warning feed rather than live telemetry; value depends on maritime scope",
    ),
    current_row(
        source_name="OpenStreetMap via Overpass API",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Mapping / Site Context",
        target_capability="Low-cost facility and feature context",
        domain="Public Record / Mapping",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Approve conditionally",
        provided_data_types="OSM military features and facilities fetched through Overpass queries",
        description="Low-cost mapping and facility context source.",
        repo_ids_or_code_paths="src/connectors/osm_military.py | app/workers/tasks.py",
        homepage_url="https://overpass-api.de/",
        registration_url="Not required",
        api_or_docs_endpoint="https://overpass-api.de/api/interpreter",
        subscription_fees_or_access_model="Free public service on shared infrastructure",
        auth_model="None",
        commercial_or_license_notes="ODbL attribution/share-alike obligations apply",
        integration_effort=LOW,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Public Overpass is best-effort; heavy production use should self-host or use managed alternatives",
    ),
    current_row(
        source_name="NASA FIRMS",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Environment / Hazard",
        target_capability="Fire and thermal anomaly alerts",
        domain="Public Record / Environmental",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Fire and thermal anomaly detections from VIIRS and MODIS",
        description="Useful environmental alert layer for wildfire and industrial heat events.",
        repo_ids_or_code_paths="src/connectors/nasa_firms.py | app/workers/tasks.py",
        homepage_url="https://firms.modaps.eosdis.nasa.gov/api/",
        registration_url="https://firms.modaps.eosdis.nasa.gov/api/map_key/",
        api_or_docs_endpoint="https://firms.modaps.eosdis.nasa.gov/api",
        subscription_fees_or_access_model="Free MAP_KEY by email signup; DEMO_KEY for lower-rate testing",
        auth_model="MAP_KEY",
        commercial_or_license_notes="Low-cost onboarding and clear rate limits",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Production use should not rely on DEMO_KEY",
    ),
    current_row(
        source_name="NOAA Space Weather Prediction Center",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Signals / Space Weather",
        target_capability="Space-weather context for GNSS and comms risk",
        domain="Public Record / Space Weather",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=LOW,
        mgmt_recommendation="Approve as standard",
        provided_data_types="Space weather alerts, warnings, watches, forecasts, and product feeds",
        description="Global context source for GNSS, comms, and satellite operations analysis.",
        repo_ids_or_code_paths="src/connectors/noaa_swpc.py | app/workers/tasks.py",
        homepage_url="https://www.swpc.noaa.gov/",
        registration_url="Optional only for email subscriptions",
        api_or_docs_endpoint="https://services.swpc.noaa.gov/",
        subscription_fees_or_access_model="Free public HTTP feeds",
        auth_model="None",
        commercial_or_license_notes="Straightforward government/public service",
        integration_effort=LOW,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Strategic value is situational, but useful for future jamming/GNSS context",
    ),
    current_row(
        source_name="OpenAQ",
        lifecycle=CURRENT_IMPLEMENTED,
        business_area="Environment / Air Quality",
        target_capability="Air-quality context around AOIs",
        domain="Public Record / Air Quality",
        repo_status="Always registered at app startup",
        runtime_surface="App startup connector + worker poller",
        mgmt_priority=LOW,
        mgmt_recommendation="Approve conditionally",
        provided_data_types="Air quality locations and measurement records",
        description="Air-quality context layer for environmental interpretation.",
        repo_ids_or_code_paths="src/connectors/openaq.py | app/workers/tasks.py",
        homepage_url="https://openaq.org/",
        registration_url="https://explore.openaq.org/register",
        api_or_docs_endpoint="https://api.openaq.org/v3",
        subscription_fees_or_access_model="General access is free; higher-limit/custom arrangements available on request",
        auth_model="API key",
        commercial_or_license_notes="Terms and rate limits are manageable",
        integration_effort=LOW,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Repo comments are stale because current hosted API docs require API keys",
    ),
    current_row(
        source_name="RapidAPI AIS (generic bbox endpoint)",
        lifecycle=CURRENT_FALLBACK,
        business_area="Maritime Intelligence",
        target_capability="Marketplace vessel tracking fallback",
        domain="Telemetry / Marketplace",
        repo_status="Worker-only when RAPID_API_KEY is configured",
        runtime_surface="Worker-only poller",
        mgmt_priority=LOW,
        mgmt_recommendation="Marketplace fallback only",
        provided_data_types="AIS vessel positions from a third-party RapidAPI marketplace endpoint",
        description="Marketplace-based maritime fallback, not a first-party source relationship.",
        repo_ids_or_code_paths="src/connectors/rapidapi_ais.py | app/workers/tasks.py",
        homepage_url="https://rapidapi.com/hub",
        registration_url="https://rapidapi.com/hub",
        api_or_docs_endpoint="Repo template: https://ais-hub.p.rapidapi.com/vessels",
        subscription_fees_or_access_model=MARKETPLACE,
        auth_model="RapidAPI key plus host header",
        commercial_or_license_notes="Terms depend on the marketplace listing owner rather than a stable vendor contract",
        integration_effort=LOW,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Keep as backup only unless a specific listing and spend model are explicitly approved",
    ),
    current_row(
        source_name="Vessel Data (RapidAPI)",
        lifecycle=CURRENT_FALLBACK,
        business_area="Maritime Intelligence",
        target_capability="Marketplace vessel data fallback",
        domain="Telemetry / Marketplace",
        repo_status="Worker-only when VESSEL_DATA_API_KEY is configured",
        runtime_surface="Worker-only poller",
        mgmt_priority=LOW,
        mgmt_recommendation="Marketplace fallback only",
        provided_data_types="Vessel positions and related vessel data via RapidAPI",
        description="Second marketplace-based vessel fallback source.",
        repo_ids_or_code_paths="src/connectors/vessel_data.py | app/workers/tasks.py",
        homepage_url="https://rapidapi.com/ai-box-ai-box-default/api/vessel-data",
        registration_url="https://rapidapi.com/ai-box-ai-box-default/api/vessel-data",
        api_or_docs_endpoint="https://vessel-data.p.rapidapi.com/vessels",
        subscription_fees_or_access_model=MARKETPLACE,
        auth_model="RapidAPI key",
        commercial_or_license_notes="Commercial terms and continuity depend on the marketplace listing owner",
        integration_effort=LOW,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Treat as backup only unless management approves the listing and spend model",
    ),
    future_row(
        source_name="Sentinel-1 via Copernicus Data Space Ecosystem",
        business_area="Construction Monitoring / Maritime / Resilience",
        target_capability="All-weather and night SAR baseline imagery",
        domain="SAR Imagery",
        runtime_surface="Planned imagery connector and dark-ship enrichment",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Sentinel-1 SAR scenes, time series, day/night and cloud-penetrating coverage",
        description="Highest-value open gap for clouded sites, flood response, and vessel monitoring when optical sources go dark.",
        repo_ids_or_code_paths=PLANNED_IMAGERY,
        homepage_url="https://dataspace.copernicus.eu/",
        registration_url="https://dataspace.copernicus.eu/",
        api_or_docs_endpoint="https://dataspace.copernicus.eu/",
        subscription_fees_or_access_model="Free/open access with registration",
        auth_model="OAuth / token-based access",
        commercial_or_license_notes="Public Copernicus source; favorable licensing profile",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Best open-source upgrade for all-weather monitoring and stub-free maritime support",
    ),
    future_row(
        source_name="ICEYE",
        business_area="Construction Monitoring / Maritime / Disaster Response",
        target_capability="Commercial high-revisit SAR imagery",
        domain="SAR Imagery",
        runtime_surface="Planned premium imagery connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Commercial SAR imagery, persistent monitoring, tasking, and analytic products",
        description="Premium SAR option for urgent monitoring, tasking, and small-area commercial use cases.",
        repo_ids_or_code_paths=PLANNED_IMAGERY,
        homepage_url="https://www.iceye.com/",
        registration_url="https://www.iceye.com/",
        api_or_docs_endpoint="https://www.iceye.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial imagery licensing and redistribution controls apply",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best fit when open SAR is insufficient on cadence or resolution",
    ),
    future_row(
        source_name="Capella Space",
        business_area="Construction Monitoring / Maritime / Defense",
        target_capability="Commercial all-weather SAR and automated tasking",
        domain="SAR Imagery",
        runtime_surface="Planned premium imagery connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Sub-meter SAR imagery, automated tasking, maritime awareness, infrastructure monitoring",
        description="Mission-speed 24/7 SAR path with maritime and infrastructure use-case alignment.",
        repo_ids_or_code_paths=PLANNED_IMAGERY,
        homepage_url="https://www.capellaspace.com/",
        registration_url="https://www.capellaspace.com/",
        api_or_docs_endpoint="https://www.capellaspace.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Contractual licensing and export/security considerations may apply",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Strong commercial option for dark-ship, port, and infrastructure workflows",
    ),
    future_row(
        source_name="Umbra",
        business_area="Construction Monitoring / Maritime / Defense",
        target_capability="Commercial responsive SAR imagery",
        domain="SAR Imagery",
        runtime_surface="Planned premium imagery connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Commercial SAR data, dwell/spotlight/scan modes, open-data program references",
        description="Responsive U.S.-based SAR provider focused on mission-ready remote sensing.",
        repo_ids_or_code_paths=PLANNED_IMAGERY,
        homepage_url="https://umbra.space/",
        registration_url="https://umbra.space/",
        api_or_docs_endpoint="https://umbra.space/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial licensing; procurement and delivery terms must be negotiated",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Useful premium SAR alternative where responsiveness matters more than open-data economics",
    ),
    future_row(
        source_name="BlackSky",
        business_area="Construction Monitoring / Security Monitoring",
        target_capability="High-cadence premium optical imagery",
        domain="Imagery",
        runtime_surface="Planned premium imagery connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Time-diverse optical imagery, tasking, AI-enhanced ISR platform outputs",
        description="Premium rapid-revisit optical source for tactical monitoring and AI-assisted workflows.",
        repo_ids_or_code_paths=PLANNED_IMAGERY,
        homepage_url="https://www.blacksky.com/",
        registration_url="https://www.blacksky.com/",
        api_or_docs_endpoint="https://www.blacksky.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial licensing and redistribution constraints apply",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Adds higher intra-day revisit than the current open optical stack",
    ),
    future_row(
        source_name="Satellogic",
        business_area="Construction Monitoring / Security Monitoring",
        target_capability="Commercial multispectral imagery and constellation access",
        domain="Imagery",
        runtime_surface="Planned premium imagery connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Multispectral imagery, Aleph Observer platform, constellation-as-a-service offerings",
        description="Additional commercial optical option for higher cadence and portfolio diversification.",
        repo_ids_or_code_paths=PLANNED_IMAGERY,
        homepage_url="https://satellogic.com/",
        registration_url="https://satellogic.com/",
        api_or_docs_endpoint="https://satellogic.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial imagery/provider licensing applies",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Useful as a competitive alternative when diversifying premium imagery suppliers",
    ),
    future_row(
        source_name="Overture Maps Buildings",
        business_area="Construction Monitoring / Site Context",
        target_capability="Global building footprints and open enrichment",
        domain="Mapping / Property",
        runtime_surface="Planned AOI enrichment connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Global building footprints, building parts, GeoParquet releases, source attribution",
        description="Open global building baseline to enrich AOIs and reduce dependence on one-off local datasets.",
        repo_ids_or_code_paths=PLANNED_CONSTRUCTION,
        homepage_url="https://docs.overturemaps.org/guides/buildings/",
        registration_url="Not required",
        api_or_docs_endpoint="https://docs.overturemaps.org/guides/buildings/",
        subscription_fees_or_access_model="Free/open public access",
        auth_model="None",
        commercial_or_license_notes="Open-data friendly; downstream attribution obligations still apply",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Best open global footprint layer for planned permit/parcel/site-enrichment work",
    ),
    future_row(
        source_name="Regrid Parcel API",
        business_area="Construction Monitoring / Property Intelligence",
        target_capability="Parcel boundaries, ownership, zoning, and matched footprints",
        domain="Property / Parcel Data",
        runtime_surface="Planned AOI enrichment and evidence-pack connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Shortlist for U.S. parcel use cases",
        provided_data_types="Parcel boundaries, ownership, building footprints, secondary addresses, zoning, monthly plans",
        description="High-signal parcel and land-intelligence source for U.S. construction and ownership workflows.",
        repo_ids_or_code_paths=PLANNED_CONSTRUCTION,
        homepage_url="https://regrid.com/parcel-api",
        registration_url="https://app.regrid.com/",
        api_or_docs_endpoint="https://regrid.com/parcel-api",
        subscription_fees_or_access_model="Free API access entry point plus monthly plans and enterprise packages",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial property-data licensing applies",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Strong near-term fit for U.S. parcels, zoning, and ownership enrichment",
    ),
    future_row(
        source_name="ATTOM Property Data API",
        business_area="Construction Monitoring / Property Intelligence",
        target_capability="U.S. parcel, ownership, sales, and neighborhood enrichment",
        domain="Property / Parcel Data",
        runtime_surface="Planned AOI enrichment and evidence-pack connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Shortlist for U.S. property enrichment",
        provided_data_types="Parcel details, ownership, lat/long, sales history, comps, schools, crime, neighborhood data",
        description="Broad U.S. property API with free trial key and strong downstream enrichment potential.",
        repo_ids_or_code_paths=PLANNED_CONSTRUCTION,
        homepage_url="https://www.attomdata.com/solutions/property-data-api/",
        registration_url="https://www.attomdata.com/solutions/property-data-api/",
        api_or_docs_endpoint="https://api.developer.attomdata.com/",
        subscription_fees_or_access_model="Free trial API key, then commercial plans",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial property-data licensing and downstream usage restrictions apply",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Good fit for evidence packs and property ownership narratives in U.S.-centric workflows",
    ),
    future_row(
        source_name="ORBCOMM AIS Data",
        business_area="Maritime Intelligence",
        target_capability="Commercial terrestrial + satellite AIS coverage",
        domain="Maritime Telemetry",
        runtime_surface="Planned maritime connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="AIS positions, vessel tracks, terrestrial and satellite coverage, fleet analytics",
        description="Established commercial maritime data provider with global coverage beyond a single free feed.",
        repo_ids_or_code_paths=PLANNED_MARITIME,
        homepage_url="https://www.orbcomm.com/en/solutions/maritime/ais-data",
        registration_url="https://www.orbcomm.com/",
        api_or_docs_endpoint="https://www.orbcomm.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial contract and downstream usage controls apply",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best upgrade path from free AIS into enterprise-grade maritime coverage",
    ),
    future_row(
        source_name="MarineTraffic Data Services / Kpler",
        business_area="Maritime Intelligence",
        target_capability="Commercial vessel tracking, port calls, and maritime analytics",
        domain="Maritime Telemetry",
        runtime_surface="Planned maritime connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="AIS vessel positions, vessel particulars, port calls, route analytics",
        description="Widely used maritime data-services platform suitable for operations and historical lookup.",
        repo_ids_or_code_paths=PLANNED_MARITIME,
        homepage_url="https://www.marinetraffic.com/en/ais-api-services",
        registration_url="https://www.kpler.com/product/maritime/data-services",
        api_or_docs_endpoint="https://www.kpler.com/product/maritime/data-services",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial contract terms apply; branding and product ownership continue to evolve",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Strong commercial alternative if AIS quality, port calls, and historical replay matter",
    ),
    future_row(
        source_name="Lloyd's List Intelligence SeaSearcher",
        business_area="Maritime Intelligence / Investigations",
        target_capability="Vessel ownership, movements, and registry intelligence",
        domain="Maritime Intelligence",
        runtime_surface="Planned investigations and vessel-intel connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Vessel registry data, ownership, movements, and maritime intelligence records",
        description="Premium vessel-intelligence source for ownership tracing and maritime investigations.",
        repo_ids_or_code_paths=PLANNED_MARITIME,
        homepage_url="https://www.lloydslistintelligence.com/products/seasearcher",
        registration_url="https://www.lloydslistintelligence.com/products/seasearcher",
        api_or_docs_endpoint="https://www.lloydslistintelligence.com/products/seasearcher",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Premium commercial intelligence product; licensing likely restrictive",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Useful when vessel provenance and ownership history matter more than raw tracks",
    ),
    future_row(
        source_name="Global Fishing Watch APIs",
        business_area="Maritime Intelligence",
        target_capability="Fishing activity, encounters, loitering, and port-visit intelligence",
        domain="Maritime Analytics",
        runtime_surface="Planned maritime analytics connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Fishing effort, vessel identity, fishing events, encounters, loitering, port visits, vessel insights",
        description="High-value maritime behavior layer that complements AIS with risk and pattern analysis.",
        repo_ids_or_code_paths=PLANNED_MARITIME,
        homepage_url="https://globalfishingwatch.org/our-apis/",
        registration_url="https://gateway.api.globalfishingwatch.org/",
        api_or_docs_endpoint="https://globalfishingwatch.org/our-apis/",
        subscription_fees_or_access_model="Free/open data with account registration, API key request, attribution, and follow-up requirements",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Open mission-aligned dataset, but usage expectations and attribution terms apply",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Best near-term upgrade for suspicious vessel behavior and transshipment analysis",
    ),
    future_row(
        source_name="Unseenlabs",
        business_area="Maritime Intelligence / Dark Ships",
        target_capability="RF-based non-cooperative vessel detection",
        domain="Maritime RF Intelligence",
        runtime_surface="Planned dark-ship enrichment connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="RF detections and maritime geolocation for dark-vessel monitoring",
        description="Useful premium path for dark ships and non-cooperative emitters beyond AIS.",
        repo_ids_or_code_paths=PLANNED_MARITIME,
        homepage_url="https://www.unseenlabs.space/",
        registration_url="https://www.unseenlabs.space/",
        api_or_docs_endpoint="https://www.unseenlabs.space/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial RF intelligence; procurement and export review may be required",
        integration_effort=HIGH,
        legal_or_procurement_risk=HIGH,
        current_repo_caveats_or_rationale="Strong but specialized option for dark-ship detection where AIS goes silent",
    ),
    future_row(
        source_name="HawkEye 360",
        business_area="Maritime Intelligence / Signals",
        target_capability="RF geolocation, GNSS interference, and non-cooperative emitter detection",
        domain="Signals / RF Intelligence",
        runtime_surface="Planned jamming replacement and dark-ship enrichment",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="RF geolocation, GNSS interference detection, emitter activity, maritime RF intelligence",
        description="Best commercial bridge between maritime dark-ship workflows and planned GNSS/jamming capabilities.",
        repo_ids_or_code_paths=PLANNED_JAMMING,
        homepage_url="https://www.he360.com/",
        registration_url="https://www.he360.com/",
        api_or_docs_endpoint="https://www.he360.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial defense-grade data; procurement and legal review required",
        integration_effort=HIGH,
        legal_or_procurement_risk=HIGH,
        current_repo_caveats_or_rationale="Top candidate to replace the GNSS jamming stub with a real external source",
    ),
    future_row(
        source_name="Vizion Container Tracking API",
        business_area="Supply Chain / Port Logistics",
        target_capability="Container tracking and milestone normalization",
        domain="Supply Chain / Maritime Logistics",
        runtime_surface="Planned supply-chain intelligence connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Container tracking events, standardized milestones, ETAs, bill-of-lading and container-based lookup",
        description="Low-friction container tracking API that complements vessel tracking with shipment-level visibility.",
        repo_ids_or_code_paths=PLANNED_SUPPLY,
        homepage_url="https://try.vizionapi.com/ocean-tracking",
        registration_url="https://www.vizionapi.com/",
        api_or_docs_endpoint="https://try.vizionapi.com/ocean-tracking",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial contract required; downstream customer-data use should be reviewed",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Strong future fit if the business expands into cargo and container status workflows",
    ),
    future_row(
        source_name="project44 Ocean Visibility",
        business_area="Supply Chain / Port Logistics",
        target_capability="Ocean shipment visibility and exception management",
        domain="Supply Chain / Maritime Logistics",
        runtime_surface="Planned supply-chain intelligence connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Carrier and forwarder connectivity, container visibility, ETAs, alerts, API delivery",
        description="Enterprise ocean visibility platform for procurement, exception management, and shipment monitoring.",
        repo_ids_or_code_paths=PLANNED_SUPPLY,
        homepage_url="https://www.project44.com/platform/visibility/ocean/",
        registration_url="https://www.project44.com/platform/visibility/ocean/",
        api_or_docs_endpoint="https://www.project44.com/platform/visibility/ocean/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Enterprise logistics platform; contractual integration terms apply",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Relevant if management wants supply-chain operations, not just ship tracking",
    ),
    future_row(
        source_name="Xeneta API",
        business_area="Supply Chain / Freight Market Intelligence",
        target_capability="Ocean and air freight rate intelligence",
        domain="Supply Chain / Freight Analytics",
        runtime_surface="Planned market-intelligence connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Ocean and air freight market data, rates, indexes, schedules, procurement analytics",
        description="Brings pricing and market intelligence into freight and procurement workflows.",
        repo_ids_or_code_paths=PLANNED_SUPPLY,
        homepage_url="https://www.xeneta.com/products/api",
        registration_url="https://www.xeneta.com/products/api",
        api_or_docs_endpoint="https://www.xeneta.com/products/api",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial benchmark data and contractual usage terms apply",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best fit if the product evolves into market-price and freight-cost decision support",
    ),
    future_row(
        source_name="Equasis",
        business_area="Maritime Intelligence / Compliance",
        target_capability="Ship and company search for ownership and compliance context",
        domain="Maritime Registry / Compliance",
        runtime_surface="Planned investigations connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Ship search, company search, maritime status and compliance context",
        description="High-value maritime ownership/compliance lookup source with free registration.",
        repo_ids_or_code_paths=PLANNED_INVEST,
        homepage_url="https://www.equasis.org/",
        registration_url="https://www.equasis.org/EquasisWeb/public/HomePage",
        api_or_docs_endpoint="https://www.equasis.org/",
        subscription_fees_or_access_model="Free/open access with registration",
        auth_model="Registered account",
        commercial_or_license_notes="Terms should be reviewed carefully before automation or redistribution",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="One of the most useful additions for vessel ownership and sanctions-adjacent investigations",
    ),
    future_row(
        source_name="FAA Data Portal",
        business_area="Aviation / Airspace",
        target_capability="Public FAA data and airspace reference material",
        domain="Aviation Data",
        runtime_surface="Planned airspace reference connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="FAA data portal access to flight information, TFR/NOTAM entrypoints, airport and aviation datasets",
        description="Best open/public starting point to replace parts of the FAA/NOTAM stub with official FAA surfaces.",
        repo_ids_or_code_paths=PLANNED_AIR,
        homepage_url="https://www.faa.gov/data",
        registration_url="Not required",
        api_or_docs_endpoint="https://www.faa.gov/data",
        subscription_fees_or_access_model="Free/open public access",
        auth_model="None",
        commercial_or_license_notes="Official U.S. government source; downstream use still needs operational fit review",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Good foundation for an official airspace/aviation replacement path",
    ),
    future_row(
        source_name="FAA SWIM / SWIFT Portal",
        business_area="Aviation / Airspace",
        target_capability="Near real-time FAA SWIM data for NOTAM and operational workflows",
        domain="Aviation Data",
        runtime_surface="Planned airspace/NOTAM replacement connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Near real-time FAA SWIM data via SWIFT portal and related services",
        description="Most direct official path to real FAA operational data rather than demo/stub logic.",
        repo_ids_or_code_paths=PLANNED_AIR,
        homepage_url="https://www.faa.gov/air_traffic/technology/swim/products/get_connected",
        registration_url="https://portal.swim.faa.gov/",
        api_or_docs_endpoint="https://www.faa.gov/air_traffic/technology/swim/products/get_connected",
        subscription_fees_or_access_model="Access request / policy review; some services via SWIFT, some via email request",
        auth_model="Approved account / portal access",
        commercial_or_license_notes="Official source, but onboarding and service access are controlled by FAA policy",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Top official replacement for the current airspace stub if management wants real NOTAM-grade data",
    ),
    future_row(
        source_name="Cirium",
        business_area="Aviation / Airspace",
        target_capability="Commercial aeronautical, schedule, and flight data",
        domain="Aviation Intelligence",
        runtime_surface="Planned aviation connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Aeronautical data, schedules, flight status, route and airport intelligence",
        description="Premium aviation data provider for schedule, route, and airport operational workflows.",
        repo_ids_or_code_paths=PLANNED_AIR,
        homepage_url="https://www.cirium.com/",
        registration_url="https://www.cirium.com/",
        api_or_docs_endpoint="https://www.cirium.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial aviation data licensing applies",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Likely best commercial complement to FAA sources when global aviation coverage is needed",
    ),
    future_row(
        source_name="FlightAware AeroAPI",
        business_area="Aviation / Airspace",
        target_capability="Flight status, tracks, alerts, and historical aviation data",
        domain="Aviation Intelligence",
        runtime_surface="Planned aviation connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Current and historical flight status, tracks, alerts, predictions, and space-based ADS-B in higher tiers",
        description="Self-serve commercial aviation API with clear pricing tiers and scalable upgrade path.",
        repo_ids_or_code_paths=PLANNED_AIR,
        homepage_url="https://www.flightaware.com/commercial/aeroapi/",
        registration_url="https://www.flightaware.com/commercial/aeroapi/",
        api_or_docs_endpoint="https://www.flightaware.com/commercial/aeroapi/",
        subscription_fees_or_access_model="Usage-based tiers; Personal no minimum, Standard $100/month minimum, Premium $1,000/month minimum plus query fees",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Tier rights differ by personal, B2C, and B2B commercialization use",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best near-term commercial upgrade if we want clearer spend control than enterprise-only aviation vendors",
    ),
    future_row(
        source_name="OAG Flight Info API",
        business_area="Aviation / Airspace",
        target_capability="Global schedules and flight status data",
        domain="Aviation Intelligence",
        runtime_surface="Planned aviation connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Flight schedules, status, changes, historical data, developer portal access",
        description="Useful for schedule-centric workflows where airline planning and route visibility matter.",
        repo_ids_or_code_paths=PLANNED_AIR,
        homepage_url="https://www.oag.com/flight-info-api",
        registration_url="https://developers.oag.com/",
        api_or_docs_endpoint="https://www.oag.com/flight-info-api",
        subscription_fees_or_access_model="Commercial API; self-serve developer environment but contract/pricing not published as a simple sheet",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial aviation licensing applies",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Strong complement when schedule fidelity matters more than raw track feeds",
    ),
    future_row(
        source_name="CelesTrak",
        business_area="Space / Orbital",
        target_capability="Live orbital data and satellite pass context",
        domain="Orbital Data",
        runtime_surface="Planned orbit-stub replacement",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Current GP element sets, OMM XML/KVN, JSON, CSV, satellite groups and orbital metadata",
        description="Best low-friction public replacement for the current local orbit stub.",
        repo_ids_or_code_paths=PLANNED_ORBIT,
        homepage_url="https://celestrak.org/NORAD/elements/index.php",
        registration_url="Not required for public queries",
        api_or_docs_endpoint="https://celestrak.org/NORAD/documentation/gp-data-formats.php",
        subscription_fees_or_access_model="Free/open public access",
        auth_model="None",
        commercial_or_license_notes="Public service; modern OMM/JSON formats are preferred for future compatibility",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="CelesTrak warns legacy 5-digit TLE assumptions break around July 20, 2026, so new work should not be TLE-only",
    ),
    future_row(
        source_name="Space-Track.org",
        business_area="Space / Orbital",
        target_capability="Authoritative space-track API and advanced orbital services",
        domain="Orbital Data",
        runtime_surface="Planned orbit-stub replacement and advanced service integration",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="REST API for GP and GP_History orbital data, conjunction products, and advanced services",
        description="Authoritative API partner for more serious orbital and conjunction workflows than a public mirror alone.",
        repo_ids_or_code_paths=PLANNED_ORBIT,
        homepage_url="https://www.space-track.org/documentation",
        registration_url="https://www.space-track.org/",
        api_or_docs_endpoint="https://www.space-track.org/documentation",
        subscription_fees_or_access_model="User approval required; core service at no cost, advanced services may require SSA sharing agreements and review",
        auth_model="Approved account",
        commercial_or_license_notes="Official access is controlled, throttled, and governed by user agreements and service rules",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best authoritative follow-on if orbit features become customer-facing and safety-relevant",
    ),
    future_row(
        source_name="LeoLabs",
        business_area="Space / Orbital",
        target_capability="Commercial space domain awareness and orbital intelligence",
        domain="Orbital Intelligence",
        runtime_surface="Planned premium orbital-intel connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Commercial LEO object catalog, radar observations, threat alerts, space traffic intelligence",
        description="Premium SSA option if the product grows beyond public GP feeds into operational orbital intelligence.",
        repo_ids_or_code_paths=PLANNED_ORBIT,
        homepage_url="https://leolabs.space/",
        registration_url="https://leolabs.space/",
        api_or_docs_endpoint="https://leolabs.space/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Commercial space-intelligence product; contract and mission scope must be reviewed",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Adds premium catalog quality and threat alerting beyond public orbital feeds",
    ),
    future_row(
        source_name="Windy Webcams API",
        business_area="Camera / Sensor Fusion",
        target_capability="Public webcam ingestion and visual site context",
        domain="Camera / Video",
        runtime_surface="Planned camera connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Webcam listings, images, timelapse embeds, public webcam catalog access",
        description="Fastest route to adding live/public camera context to ports, sites, and chokepoints.",
        repo_ids_or_code_paths=PLANNED_CAMERA,
        homepage_url="https://api.windy.com/webcams",
        registration_url="https://api.windy.com/webcams/pricing",
        api_or_docs_endpoint="https://api.windy.com/webcams",
        subscription_fees_or_access_model="Free tier plus Professional at 9,990 EUR/year for unrestricted API access",
        auth_model="API key",
        commercial_or_license_notes="Terms of use and media embedding constraints should be reviewed",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best public-camera source for future video and absence-as-signal workflows",
    ),
    future_row(
        source_name="Verkada API",
        business_area="Camera / Sensor Fusion",
        target_capability="Enterprise private camera integration",
        domain="Camera / Video",
        runtime_surface="Planned camera connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Camera device inventory, metadata, site/location details, enterprise camera control surfaces",
        description="Private-enterprise camera API path for customer deployments, unlike public webcam sources.",
        repo_ids_or_code_paths=PLANNED_CAMERA,
        homepage_url="https://apidocs.verkada.com/reference/getcamerainfoviewv1",
        registration_url="https://www.verkada.com/",
        api_or_docs_endpoint="https://api.verkada.com/cameras/v1/devices",
        subscription_fees_or_access_model="Commercial enterprise platform; contact sales / customer account required",
        auth_model="Account + API key / token",
        commercial_or_license_notes="Enterprise SaaS and security review required",
        integration_effort=HIGH,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Best fit for private customer camera networks rather than public monitoring",
    ),
    future_row(
        source_name="UCDP API",
        business_area="Conflict / Crisis Intelligence",
        target_capability="Academic-grade conflict event and fatalities data",
        domain="Conflict Data",
        runtime_surface="Planned strike/conflict connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Georeferenced event data, yearly conflict datasets, fatalities, actors, geographies",
        description="Strong research-grade complement to ACLED, especially for historical and academic use cases.",
        repo_ids_or_code_paths=PLANNED_STRIKE,
        homepage_url="https://ucdp.uu.se/apidocs/index.html",
        registration_url="https://ucdp.uu.se/apidocs/index.html",
        api_or_docs_endpoint="https://ucdpapi.pcr.uu.se/api/",
        subscription_fees_or_access_model="Free of charge; token-based authenticated access introduced in February 2026",
        auth_model="x-ucdp-access-token",
        commercial_or_license_notes="Academic/research-oriented source; intended-use review is still advisable",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Top future candidate to reduce dependence on a single conflict-event vendor",
    ),
    future_row(
        source_name="SIPRI Arms Transfers Database",
        business_area="Conflict / Defense Intelligence",
        target_capability="Arms-transfer context and defense trade research",
        domain="Defense / Conflict Data",
        runtime_surface="Planned evidence-pack enrichment",
        mgmt_priority=LOW,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Arms-transfer records and defense trade context",
        description="Useful strategic context source for defense-supply and conflict reconstruction narratives.",
        repo_ids_or_code_paths=PLANNED_STRIKE,
        homepage_url="https://www.sipri.org/databases/armstransfers",
        registration_url="https://www.sipri.org/databases/armstransfers",
        api_or_docs_endpoint="https://www.sipri.org/databases/armstransfers",
        subscription_fees_or_access_model="Public research database access",
        auth_model="Varies by access path",
        commercial_or_license_notes="Research database; downstream commercial use should be reviewed",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="More valuable for analyst workflows than for real-time alerting",
    ),
    future_row(
        source_name="Janes",
        business_area="Conflict / Defense Intelligence",
        target_capability="Premium defense and military intelligence",
        domain="Defense Intelligence",
        runtime_surface="Planned analyst/evidence-pack connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Commercial shortlist",
        provided_data_types="Defense intelligence, platform data, military capability and risk reporting",
        description="Premium defense-intelligence layer for high-end analyst and evidence-pack workflows.",
        repo_ids_or_code_paths=PLANNED_STRIKE,
        homepage_url="https://www.janes.com/",
        registration_url="https://www.janes.com/",
        api_or_docs_endpoint="https://www.janes.com/",
        subscription_fees_or_access_model=QUOTE_BASED,
        auth_model="Account + API key / token",
        commercial_or_license_notes="Premium licensed intelligence product with likely restrictive terms",
        integration_effort=HIGH,
        legal_or_procurement_risk=HIGH,
        current_repo_caveats_or_rationale="High value for analysts, but likely too expensive for broad platform defaulting",
    ),
    future_row(
        source_name="ReliefWeb API",
        business_area="Crisis / Humanitarian Intelligence",
        target_capability="Humanitarian reports, jobs, maps, and curated crisis content",
        domain="Crisis / Humanitarian Data",
        runtime_surface="Planned context connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Curated reports, maps, jobs, training, organizations, and crisis content",
        description="Strong humanitarian and disaster-response context layer to complement conflict data.",
        repo_ids_or_code_paths=PLANNED_INVEST,
        homepage_url="https://apidoc.reliefweb.int/index.html",
        registration_url="https://apidoc.reliefweb.int/index.html",
        api_or_docs_endpoint="https://api.reliefweb.int/v2/",
        subscription_fees_or_access_model="Public read-only API; approved appname required from November 1, 2025",
        auth_model="appname parameter",
        commercial_or_license_notes="Open/public API with usage identification requirements",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Good addition for crisis context and evidence packs in humanitarian settings",
    ),
    future_row(
        source_name="GDACS",
        business_area="Disaster / Crisis Intelligence",
        target_capability="Global disaster alerts, feeds, and impact context",
        domain="Disaster Alerts",
        runtime_surface="Planned hazard/context connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Disaster alerts, RSS feeds, GeoJSON/web API, impact context for earthquakes, cyclones, floods, volcanoes",
        description="High-signal disaster alerting source with feed and API options for rapid crisis context.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://www.gdacs.org/",
        registration_url="https://www.gdacs.org/feed_reference.aspx",
        api_or_docs_endpoint="https://www.gdacs.org/gdacsapi/swagger/index.html",
        subscription_fees_or_access_model="Free GDACS data; source acknowledgment requested",
        auth_model="None",
        commercial_or_license_notes="Use is subject to disclaimer and attribution expectations",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Useful for disaster-alert workflows not covered by the current hazard stack alone",
    ),
    future_row(
        source_name="OpenCorporates API",
        business_area="Investigations / Entity Resolution",
        target_capability="Corporate ownership and registration lookup",
        domain="Corporate Registry / Compliance",
        runtime_surface="Planned investigations connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Company registry data, officers, filings, provenance, and open/commercial access options",
        description="Best general-purpose corporate registry layer for vessel/company ownership tracing.",
        repo_ids_or_code_paths=PLANNED_INVEST,
        homepage_url="https://api.opencorporates.com/",
        registration_url="https://api.opencorporates.com/",
        api_or_docs_endpoint="https://api.opencorporates.com/",
        subscription_fees_or_access_model="Open-data access plus commercial access options",
        auth_model="Varies by plan / API usage",
        commercial_or_license_notes="Open data is share-alike attribution; commercial arrangements are available",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Top candidate for entity-resolution and ownership workflows",
    ),
    future_row(
        source_name="GLEIF API",
        business_area="Investigations / Entity Resolution",
        target_capability="LEI-based entity resolution and parent-child lookup",
        domain="Corporate Registry / Compliance",
        runtime_surface="Planned investigations connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="LEI reference data, ownership data, fuzzy matching, mapped identifiers, parent/child relationships",
        description="Best source for normalized legal-entity identity and corporate structure resolution.",
        repo_ids_or_code_paths=PLANNED_INVEST,
        homepage_url="https://www.gleif.org/en/lei-data/gleif-api",
        registration_url="https://www.gleif.org/en/lei-data/gleif-api",
        api_or_docs_endpoint="https://api.gleif.org/",
        subscription_fees_or_access_model="Public production API",
        auth_model="None",
        commercial_or_license_notes="Open/public identity infrastructure with favorable terms",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Strong complement to OpenCorporates for higher-confidence entity resolution",
    ),
    future_row(
        source_name="OFAC Sanctions List Service",
        business_area="Compliance / Investigations",
        target_capability="Sanctions screening for vessels, entities, and aircraft",
        domain="Sanctions / Compliance",
        runtime_surface="Planned compliance connector",
        mgmt_priority=HIGH,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="SDN list, consolidated non-SDN lists, customizable datasets, maritime vessels and aircraft on sanctions lists",
        description="Core U.S. sanctions-screening source for compliance-aware investigations and alerts.",
        repo_ids_or_code_paths=PLANNED_INVEST,
        homepage_url="https://ofac.treasury.gov/sanctions-list-service",
        registration_url="Not required",
        api_or_docs_endpoint="https://sanctionslist.ofac.treas.gov/",
        subscription_fees_or_access_model="Free official sanctions list service",
        auth_model="None",
        commercial_or_license_notes="Official U.S. government sanctions source; must be interpreted with compliance counsel as needed",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Highest-value compliance addition for dark ships and ownership-based investigations",
    ),
    future_row(
        source_name="UN Security Council Sanctions Lists",
        business_area="Compliance / Investigations",
        target_capability="UN sanctions screening and cross-jurisdiction context",
        domain="Sanctions / Compliance",
        runtime_surface="Planned compliance connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="UN sanctions list materials and committee-maintained sanctions information",
        description="Useful global sanctions complement to OFAC in multinational compliance workflows.",
        repo_ids_or_code_paths=PLANNED_INVEST,
        homepage_url="https://main.un.org/securitycouncil/en/sanctions/1267/aq_sanctions_list",
        registration_url="Not required",
        api_or_docs_endpoint="https://main.un.org/securitycouncil/en/sanctions/1267/aq_sanctions_list",
        subscription_fees_or_access_model="Free official UN publication access",
        auth_model="None",
        commercial_or_license_notes="Official international-government source",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Adds cross-border compliance value when a U.S.-only sanctions view is not enough",
    ),
    future_row(
        source_name="Copernicus Marine",
        business_area="Environment / Maritime Operations",
        target_capability="Oceanographic, marine forecast, and observation context",
        domain="Marine / Ocean Data",
        runtime_surface="Planned marine-context connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Marine numerical models, satellite and in situ observations, subsets and original files",
        description="Best open marine-context upgrade for ports, routing, and environmental interpretation.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://help.marine.copernicus.eu/en/articles/7949409-copernicus-marine-toolbox-introduction",
        registration_url="https://data.marine.copernicus.eu/",
        api_or_docs_endpoint="https://data.marine.copernicus.eu/",
        subscription_fees_or_access_model="Free account-based access; toolbox advertises no quotas on volume/bandwidth",
        auth_model="Copernicus Marine account",
        commercial_or_license_notes="Strong public-data option; attribution requirements still apply",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="High utility for maritime and weather-aware workflows beyond basic forecasts",
    ),
    future_row(
        source_name="GloFAS",
        business_area="Environment / Resilience",
        target_capability="Flood forecasting and flood-impact context",
        domain="Flood Data",
        runtime_surface="Planned hazard connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Medium-range flood forecasts, seasonal forecasts, impact forecasts, monitoring APIs and services",
        description="Open flood-intelligence layer for site disruption, corridor risk, and disaster workflows.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://global-flood.emergency.copernicus.eu/general-information/data-and-services/",
        registration_url="https://global-flood.emergency.copernicus.eu/general-information/data-and-services/",
        api_or_docs_endpoint="https://global-flood.emergency.copernicus.eu/general-information/data-and-services/",
        subscription_fees_or_access_model="Public services plus request-based access for some download channels",
        auth_model="Varies by access path",
        commercial_or_license_notes="Copernicus public service; terms depend on delivery method",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Useful for flood-sensitive construction, logistics, and resilience analysis",
    ),
    future_row(
        source_name="Copernicus Climate Data Store / ERA5",
        business_area="Environment / Climate Context",
        target_capability="Historical reanalysis and climate baselines",
        domain="Climate / Weather Data",
        runtime_surface="Planned climate-context connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Climate and weather reanalysis datasets including ERA5 and related climate products",
        description="Best open historical weather/climate baseline for retrospective analyses and evidence packs.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://cds.climate.copernicus.eu/",
        registration_url="https://cds.climate.copernicus.eu/",
        api_or_docs_endpoint="https://cds.climate.copernicus.eu/",
        subscription_fees_or_access_model="Public account-based access",
        auth_model="Registered account / CDS API",
        commercial_or_license_notes="Public climate data program with favorable licensing profile",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Important if management wants historical weather/climate evidence, not just forecasts",
    ),
    future_row(
        source_name="ECMWF Open Data",
        business_area="Environment / Weather Operations",
        target_capability="High-quality real-time weather forecast data",
        domain="Weather Data",
        runtime_surface="Planned forecast connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="IFS and AIFS forecast data, rolling archive, open data and broader real-time catalogue access",
        description="Higher-quality meteorological input option if forecast fidelity becomes a competitive need.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://www.ecmwf.int/en/forecasts/datasets/open-data",
        registration_url="https://www.ecmwf.int/en/forecasts/datasets/open-data",
        api_or_docs_endpoint="https://www.ecmwf.int/en/forecasts/datasets/open-data",
        subscription_fees_or_access_model="Free/open subset under CC BY 4.0; service charges may apply for high-volume delivery and custom access",
        auth_model="Varies by delivery path",
        commercial_or_license_notes="Open licensing is favorable, but bulk delivery/service access may still cost money",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Worth evaluating if Open-Meteo proves too thin for premium operational weather workflows",
    ),
    future_row(
        source_name="Copernicus DEM",
        business_area="Terrain / Site Analysis",
        target_capability="Elevation, terrain, and line-of-sight context",
        domain="Terrain / Elevation Data",
        runtime_surface="Planned terrain connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Digital surface model capturing terrain and infrastructure",
        description="Good terrain/elevation layer for visibility, slope, and site-access analysis.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://dataspace.copernicus.eu/news/2024-5-22-copernicus-digital-elevation-model-dem-now-available-copernicus-data-space-ecosystem",
        registration_url="https://dataspace.copernicus.eu/",
        api_or_docs_endpoint="https://dataspace.copernicus.eu/",
        subscription_fees_or_access_model="Free/open access with registration",
        auth_model="CDSE account / access flow",
        commercial_or_license_notes="Public Copernicus program data",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Good complement to imagery when terrain and infrastructure height matter",
    ),
    future_row(
        source_name="NASA SRTM",
        business_area="Terrain / Site Analysis",
        target_capability="Global elevation baseline",
        domain="Terrain / Elevation Data",
        runtime_surface="Planned terrain connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Global digital elevation model data from Shuttle Radar Topography Mission",
        description="Well-known open elevation baseline for terrain, line-of-sight, and route analysis.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://www.earthdata.nasa.gov/data/instruments/srtm",
        registration_url="https://urs.earthdata.nasa.gov/",
        api_or_docs_endpoint="https://www.earthdata.nasa.gov/data/instruments/srtm",
        subscription_fees_or_access_model="Open NASA data; Earthdata Login often required for downloads/tools",
        auth_model="Earthdata Login",
        commercial_or_license_notes="Favorable NASA open-data profile",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Reliable low-cost terrain layer where Copernicus DEM is not preferred",
    ),
    future_row(
        source_name="GEDI",
        business_area="Terrain / Vegetation / Site Analysis",
        target_capability="Vegetation structure and surface-elevation context",
        domain="Lidar / Vegetation Structure",
        runtime_surface="Planned environmental enrichment connector",
        mgmt_priority=LOW,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Lidar footprint and gridded products for forest vertical structure and surface elevation",
        description="Useful for vegetation and canopy structure context, especially in environmental or concealment-sensitive analyses.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://www.earthdata.nasa.gov/data/projects/gedi",
        registration_url="https://urs.earthdata.nasa.gov/",
        api_or_docs_endpoint="https://www.earthdata.nasa.gov/data/instruments/gedi-lidar",
        subscription_fees_or_access_model="Open NASA data; Earthdata Login and cloud/search tooling apply",
        auth_model="Earthdata Login",
        commercial_or_license_notes="Favorable NASA open-data profile",
        integration_effort=HIGH,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Lower priority than DEM/SAR, but valuable for niche terrain and vegetation analysis",
    ),
    future_row(
        source_name="NASA Black Marble",
        business_area="Environment / Infrastructure Resilience",
        target_capability="Nighttime lights and outage/change context",
        domain="Nighttime Lights",
        runtime_surface="Planned contextual imagery connector",
        mgmt_priority=MEDIUM,
        mgmt_recommendation="Strong shortlist",
        provided_data_types="Nighttime lights products and related tools for power-outage and urban-activity analysis",
        description="Excellent future layer for outage detection, urban growth, and activity baselining.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://www.earthdata.nasa.gov/topics/human-dimensions/nighttime-lights",
        registration_url="https://urs.earthdata.nasa.gov/",
        api_or_docs_endpoint="https://www.earthdata.nasa.gov/topics/human-dimensions/nighttime-lights",
        subscription_fees_or_access_model="NASA data are openly available; Earthdata Login is required for downloads and some tools",
        auth_model="Earthdata Login",
        commercial_or_license_notes="Open NASA data with favorable usage terms",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Strong future signal for outages and urban activity not visible in daytime imagery alone",
    ),
    future_row(
        source_name="EOG VIIRS Nighttime Lights",
        business_area="Environment / Infrastructure Resilience",
        target_capability="Derived nighttime-lights analytics",
        domain="Nighttime Lights",
        runtime_surface="Planned contextual imagery connector",
        mgmt_priority=LOW,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="VIIRS nighttime light products and derivative layers",
        description="Useful derived nighttime-lights source that can complement NASA Earthdata distribution paths.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://eogdata.mines.edu/products/vnl/",
        registration_url="https://eogdata.mines.edu/products/vnl/",
        api_or_docs_endpoint="https://eogdata.mines.edu/products/vnl/",
        subscription_fees_or_access_model="Public academic-style access; confirm operational/commercial usage expectations",
        auth_model="Varies by download path",
        commercial_or_license_notes="Check downstream usage terms for commercial productization",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=MEDIUM,
        current_repo_caveats_or_rationale="Secondary option behind NASA Earthdata, especially if derived products are more convenient",
    ),
    future_row(
        source_name="GEBCO Gridded Bathymetry Data",
        business_area="Maritime / Ocean Terrain",
        target_capability="Seafloor and bathymetry context",
        domain="Bathymetry / Ocean Terrain",
        runtime_surface="Planned maritime/environment connector",
        mgmt_priority=LOW,
        mgmt_recommendation="Research and shortlist",
        provided_data_types="Global gridded bathymetry, regional grids, web services, and OPeNDAP access",
        description="Useful for seabed, route, and maritime terrain context in chokepoint or undersea analyses.",
        repo_ids_or_code_paths=PLANNED_ENV,
        homepage_url="https://www.gebco.net/data-products/gridded-bathymetry-data",
        registration_url="Not required",
        api_or_docs_endpoint="https://www.gebco.net/data-products/gridded-bathymetry-data",
        subscription_fees_or_access_model="Public domain and free of charge",
        auth_model="None",
        commercial_or_license_notes="Public-domain style terms with attribution request",
        integration_effort=MEDIUM,
        legal_or_procurement_risk=LOW,
        current_repo_caveats_or_rationale="Niche, but relevant if maritime analysis expands below surface-level monitoring",
    ),
]


COLUMN_WIDTHS = [
    34, 18, 24, 30, 20, 30, 28, 14, 24, 34, 40, 38,
    30, 28, 32, 34, 20, 34, 18, 20, 42, 14, 20, 28,
]
